---
title: "&#39; Throw &#39; deyimi dışında işleneni atlayın olamaz bir &#39; Catch &#39; deyim veya iç bir &#39; Son olarak &#39; deyimi"
ms.date: 07/20/2015
ms.prod: .net
ms.technology:
- devlang-visual-basic
ms.topic: article
f1_keywords:
- vbc30666
- bc30666
helpviewer_keywords:
- BC30666
ms.assetid: a208a6ea-0e36-4bf1-8984-4de1a0e38a2a
caps.latest.revision: 
author: dotnet-bot
ms.author: dotnetcontent
ms.openlocfilehash: 5fa3be0ca47a4158b3abeef9801148e3f19d3b36
ms.sourcegitcommit: c0dd436f6f8f44dc80dc43b07f6841a00b74b23f
ms.translationtype: MT
ms.contentlocale: tr-TR
ms.lasthandoff: 01/19/2018
---
# <a name="39throw39-statement-cannot-omit-operand-outside-a-39catch39-statement-or-inside-a-39finally39-statement"></a>&#39; Throw &#39; deyimi dışında işleneni atlayın olamaz bir &#39; Catch &#39; deyim veya iç bir &#39; Son olarak &#39; deyimi
`Throw`deyimleri dışında `Catch` deyimi bir özel durum nesnesi adı sağlamanız gerekir.  
  
 **Hata Kimliği:** BC30666  
  
## <a name="to-correct-this-error"></a>Bu hatayı düzeltmek için  
  
1.  Türetilen bir özel durum nesnesinin adını belirleyin `System.Exception`.  
  
2.  Kodunuzu yeniden yapılandırmayı böylece `Throw` açıklamadır içinde bir `Catch` bloğu.  
  
## <a name="see-also"></a>Ayrıca Bkz.  
 [Throw Deyimi](../../visual-basic/language-reference/statements/throw-statement.md)  
 [Try...Catch...Finally Deyimi](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)  
 [Visual Basic'te özel durum sınıfı](http://msdn.microsoft.com/library/9aac396f-34ca-4afb-8e6c-e523cb690ba9)  
 [Özel durum ve hata Visual Basic'te işleme](http://msdn.microsoft.com/library/3e351e73-cf23-40ab-8b60-05794160529e)
