---
title: "&#39; Catch &#39; hiçbir zaman sınırına blok; &lt;özel durum&gt; yukarıda aynı &#39; işlenen Try &#39; deyimi"
ms.date: 07/20/2015
ms.prod: .net
ms.technology: devlang-visual-basic
ms.topic: article
f1_keywords:
- bc42031
- vbc42031
helpviewer_keywords: BC42031
ms.assetid: 7d15597c-5988-42ea-a853-63cbf78faaf3
caps.latest.revision: "10"
author: dotnet-bot
ms.author: dotnetcontent
ms.openlocfilehash: b32e37f9dadaa43250906cf1d760f279754c60b0
ms.sourcegitcommit: c0dd436f6f8f44dc80dc43b07f6841a00b74b23f
ms.translationtype: MT
ms.contentlocale: tr-TR
ms.lasthandoff: 01/19/2018
---
# <a name="39catch39-block-never-reached-ltexceptiongt-handled-above-in-the-same-39try39-statement"></a>&#39; Catch &#39; hiçbir zaman sınırına blok; &lt;özel durum&gt; yukarıda aynı &#39; işlenen Try &#39; deyimi
A `Catch` bir önceki işlendiğinden kod bloğunda ulaşılamıyor `Try` bloğu.  
  
 Varsayılan olarak, bu iletiyi bir uyarıdır. Uyarıları gizleme veya uyarıları hata olarak davranma hakkında daha fazla bilgi için lütfen bkz [Visual Basic'te uyarıları yapılandırma](/visualstudio/ide/configuring-warnings-in-visual-basic)  
  
 **Hata Kimliği:** BC42031  
  
## <a name="to-correct-this-error"></a>Bu hatayı düzeltmek için  
  
-   Yedek deyimi kaldırın.  
  
## <a name="see-also"></a>Ayrıca Bkz.  
 [Nasıl yapılır: Visual Basic'te bir özel durum yakalama](http://msdn.microsoft.com/library/f3063c89-d2bf-49b1-91b5-b87edfb18b95)  
 [Nasıl yapılır: Test kodu ile bir Try... Visual Basic'te catch bloğu](http://msdn.microsoft.com/library/8368e205-ed73-4185-a247-af84fb4fafa9)  
 [Nasıl yapılır: Visual Basic'te bir Catch bloğunun hataları filtre](http://msdn.microsoft.com/library/85964d0a-56e7-4301-a96e-5eaea23b7b9b)  
 [İzlenecek yol: Yapılandırılmış özel durum işleme (Visual Basic)](http://msdn.microsoft.com/library/440da655-4b32-490b-8b16-bfe46f41fa76)  
 [Try...Catch...Finally Deyimi](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
