---
title: Özel Durumlar
ms.date: 03/30/2017
ms.assetid: 065205cc-52dd-4f30-9578-b17d8d113136
ms.openlocfilehash: cfeefcd29dc05ed5e325950194d9f0775b1fa9fa
ms.sourcegitcommit: 3d5d33f384eeba41b2dff79d096f47ccc8d8f03d
ms.translationtype: MT
ms.contentlocale: tr-TR
ms.lasthandoff: 05/04/2018
ms.locfileid: "33520165"
---
# <a name="exceptions"></a><span data-ttu-id="0746f-102">Özel Durumlar</span><span class="sxs-lookup"><span data-stu-id="0746f-102">Exceptions</span></span>
<span data-ttu-id="0746f-103">İş akışları kullanabilirsiniz <xref:System.Activities.Statements.TryCatch> bir iş akışı yürütme sırasında başlatılan özel durumları işleme etkinlik.</span><span class="sxs-lookup"><span data-stu-id="0746f-103">Workflows can use the <xref:System.Activities.Statements.TryCatch> activity to handle exceptions that are raised during the execution of a workflow.</span></span> <span data-ttu-id="0746f-104">Bu özel durumlar işlenebilir veya bunlar kullanarak yeniden atılabilen <xref:System.Activities.Statements.Rethrow> etkinlik.</span><span class="sxs-lookup"><span data-stu-id="0746f-104">These exceptions can be handled or they can be re-thrown using the <xref:System.Activities.Statements.Rethrow> activity.</span></span> <span data-ttu-id="0746f-105">Etkinlikler <xref:System.Activities.Statements.TryCatch.Finally%2A> bölümü olan yürütülmesi ya da <xref:System.Activities.Statements.TryCatch.Try%2A> bölüm veya <xref:System.Activities.Statements.TryCatch.Catches%2A> bölüm tamamlar.</span><span class="sxs-lookup"><span data-stu-id="0746f-105">Activities in the <xref:System.Activities.Statements.TryCatch.Finally%2A> section are executed when either the <xref:System.Activities.Statements.TryCatch.Try%2A> section or the <xref:System.Activities.Statements.TryCatch.Catches%2A> section completes.</span></span> <span data-ttu-id="0746f-106">İş akışları tarafından barındırılan bir <xref:System.Activities.WorkflowApplication> örneği de kullanabilir <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> tarafından işlenmemiş özel durumları işlemek için olay işleyicisi bir <xref:System.Activities.Statements.TryCatch> etkinlik.</span><span class="sxs-lookup"><span data-stu-id="0746f-106">Workflows hosted by a <xref:System.Activities.WorkflowApplication> instance can also use the <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> event handler to handle exceptions that are not handled by a <xref:System.Activities.Statements.TryCatch> activity.</span></span>  
  
## <a name="causes-of-exceptions"></a><span data-ttu-id="0746f-107">Özel durumlar nedenleri</span><span class="sxs-lookup"><span data-stu-id="0746f-107">Causes of Exceptions</span></span>  
 <span data-ttu-id="0746f-108">Bir iş akışında, özel durumlar aşağıdaki yollarla oluşturulabilir:</span><span class="sxs-lookup"><span data-stu-id="0746f-108">In a workflow, exceptions can be generated in the following ways:</span></span>  
  
-   <span data-ttu-id="0746f-109">Bir zaman aşımı işlemlerinde <xref:System.Activities.Statements.TransactionScope>.</span><span class="sxs-lookup"><span data-stu-id="0746f-109">A time-out of transactions in <xref:System.Activities.Statements.TransactionScope>.</span></span>  
  
-   <span data-ttu-id="0746f-110">İş akışını kullanarak oluşturulan bir açık özel <xref:System.Activities.Statements.Throw> etkinlik.</span><span class="sxs-lookup"><span data-stu-id="0746f-110">An explicit exception thrown by the workflow using the <xref:System.Activities.Statements.Throw> activity.</span></span>  
  
-   <span data-ttu-id="0746f-111">A [!INCLUDE[netfx_current_short](../../../includes/netfx-current-short-md.md)] bir etkinlikten özel durum oluştu.</span><span class="sxs-lookup"><span data-stu-id="0746f-111">A [!INCLUDE[netfx_current_short](../../../includes/netfx-current-short-md.md)] exception thrown from an activity.</span></span>  
  
-   <span data-ttu-id="0746f-112">Kitaplıklar, bileşenleri veya iş akışında kullanılan hizmetleri gibi dış koddan bir özel durum oluştu.</span><span class="sxs-lookup"><span data-stu-id="0746f-112">An exception thrown from external code, such as libraries, components, or services that are used in the workflow.</span></span>  
  
## <a name="handling-exceptions"></a><span data-ttu-id="0746f-113">Özel Durumları İşleme</span><span class="sxs-lookup"><span data-stu-id="0746f-113">Handling Exceptions</span></span>  
 <span data-ttu-id="0746f-114">Bir özel durum etkinlik tarafından oluşturulan ve işlenmeyen ise, varsayılan iş akışı örneği sonlandırılacak davranıştır.</span><span class="sxs-lookup"><span data-stu-id="0746f-114">If an exception is thrown by an activity and is unhandled, the default behavior is to terminate the workflow instance.</span></span> <span data-ttu-id="0746f-115">Özel bir varsa <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> işleyici varsa, bu varsayılan davranışı geçersiz kılabilirsiniz.</span><span class="sxs-lookup"><span data-stu-id="0746f-115">If a custom <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> handler is present, it can override this default behavior.</span></span> <span data-ttu-id="0746f-116">Bu işleyici, iş akışı ana Yazar özel günlüğü, iş akışı iptal etme, iş akışı iptal etme veya iş akışının sonlandırma gibi uygun işleme sağlamak için fırsatı sunar.</span><span class="sxs-lookup"><span data-stu-id="0746f-116">This handler gives the workflow host author an opportunity to provide the appropriate handling, such as custom logging, aborting the workflow, canceling the workflow, or terminating the workflow.</span></span>  <span data-ttu-id="0746f-117">Bir iş akışı işlenmiyor, bir özel durum geçirirse <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> işleyici çağrılır.</span><span class="sxs-lookup"><span data-stu-id="0746f-117">If a workflow raises an exception that is not handled, the <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> handler is invoked.</span></span> <span data-ttu-id="0746f-118">Döndürülen üç olası eylemler vardır <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> iş akışının nihai sonucu belirleyin.</span><span class="sxs-lookup"><span data-stu-id="0746f-118">There are three possible actions returned from <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> which determine the final outcome of the workflow.</span></span>  
  
-   <span data-ttu-id="0746f-119">**İptal** -normal çıkış şube yürütme iptal edilen iş akışı örneğidir.</span><span class="sxs-lookup"><span data-stu-id="0746f-119">**Cancel** - A cancelled workflow instance is a graceful exit of a branch execution.</span></span> <span data-ttu-id="0746f-120">(Örneğin, bir CancellationScope etkinliğini kullanarak) için İptali davranışı model oluşturabilirsiniz.</span><span class="sxs-lookup"><span data-stu-id="0746f-120">You can model cancelation behavior (for example, by using a CancellationScope activity).</span></span> <span data-ttu-id="0746f-121">İptal işlemi tamamlandığında tamamlanan işleyici çağrılır.</span><span class="sxs-lookup"><span data-stu-id="0746f-121">The Completed handler is invoked when the cancellation process completes.</span></span> <span data-ttu-id="0746f-122">İptal edilen bir iş akışı iptal edildi durumda değil.</span><span class="sxs-lookup"><span data-stu-id="0746f-122">A cancelled workflow is in the Cancelled state.</span></span>  
  
-   <span data-ttu-id="0746f-123">**Sonlandırma** -Sonlandırılan İş akışı örneği yeniden veya sürdürülemez.</span><span class="sxs-lookup"><span data-stu-id="0746f-123">**Terminate** - A terminated workflow instance cannot be resumed or restarted.</span></span>  <span data-ttu-id="0746f-124">Bu, özel bir durum sona erdirildi neden olarak sağlayabilir tamamlanan olay tetiklenir.</span><span class="sxs-lookup"><span data-stu-id="0746f-124">This triggers the Completed event in which you can provide an exception as the reason it was terminated.</span></span> <span data-ttu-id="0746f-125">Sonlandırma işlemi tamamlandığında kesildi işleyici çağrılır.</span><span class="sxs-lookup"><span data-stu-id="0746f-125">The Terminated handler is invoked when the termination process completes.</span></span> <span data-ttu-id="0746f-126">Sonlandırılmış bir iş akışı Faulted durumda değil.</span><span class="sxs-lookup"><span data-stu-id="0746f-126">A terminated workflow is in the Faulted state.</span></span>  
  
-   <span data-ttu-id="0746f-127">**Abort** -yalnızca onu kalıcı olması için yapılandırılmışsa, durdurulan iş akışı örnekleri sürdürüldü.</span><span class="sxs-lookup"><span data-stu-id="0746f-127">**Abort** - An aborted workflow instances can be resumed only if it has been configured to be persistent.</span></span>  <span data-ttu-id="0746f-128">Kalıcı bir iş akışı devam ettirilemez.</span><span class="sxs-lookup"><span data-stu-id="0746f-128">Without persistence, a workflow cannot be resumed.</span></span>  <span data-ttu-id="0746f-129">Bir noktada bir iş akışı son Kalıcılık noktası kaybolacak bu yana (bellekte) tüm işleri iptal edilir.</span><span class="sxs-lookup"><span data-stu-id="0746f-129">At the point a workflow is aborted, any work done (in memory) since the last persistence point will be lost.</span></span> <span data-ttu-id="0746f-130">Durdurulan iş akışı için İptal işlemi tamamlandığında kullanarak özel durum neden iptal edildi işleyici çağrılır.</span><span class="sxs-lookup"><span data-stu-id="0746f-130">For an aborted workflow, the Aborted handler is invoked using the exception as the reason when the abort process completes.</span></span> <span data-ttu-id="0746f-131">Ancak, iptal edildi ve kesildi aksine, tamamlandı işleyici çağrılır.</span><span class="sxs-lookup"><span data-stu-id="0746f-131">However, unlike Cancelled and Terminated, the Completed handler is not invoked.</span></span> <span data-ttu-id="0746f-132">İptal edilen bir iş akışı bir iptal edildi durumda.</span><span class="sxs-lookup"><span data-stu-id="0746f-132">An aborted workflow is in an Aborted state.</span></span>  
  
 <span data-ttu-id="0746f-133">Aşağıdaki örnek aykırı bir iş akışını çağırır.</span><span class="sxs-lookup"><span data-stu-id="0746f-133">The following example invokes a workflow that throws an exception.</span></span> <span data-ttu-id="0746f-134">Özel iş akışı tarafından işlenmeyen ve <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> işleyici çağrılır.</span><span class="sxs-lookup"><span data-stu-id="0746f-134">The exception is unhandled by the workflow and the <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> handler is invoked.</span></span> <span data-ttu-id="0746f-135"><xref:System.Activities.WorkflowApplicationUnhandledExceptionEventArgs> Özel durum hakkında bilgi sağlamak için denetlenir ve iş akışı sonlandırılır.</span><span class="sxs-lookup"><span data-stu-id="0746f-135">The <xref:System.Activities.WorkflowApplicationUnhandledExceptionEventArgs> are inspected to provide information about the exception, and the workflow is terminated.</span></span>  
  
 [!code-csharp[CFX_WorkflowApplicationExample#1](../../../samples/snippets/csharp/VS_Snippets_CFX/cfx_workflowapplicationexample/cs/program.cs#1)]  
  
### <a name="handling-exceptions-with-the-trycatch-activity"></a><span data-ttu-id="0746f-136">TryCatch aktivitesiyle özel durumları işleme</span><span class="sxs-lookup"><span data-stu-id="0746f-136">Handling Exceptions with the TryCatch Activity</span></span>  
 <span data-ttu-id="0746f-137">Bir iş akışı içinde özel durumları işleme ile gerçekleştirilir <xref:System.Activities.Statements.TryCatch> etkinlik.</span><span class="sxs-lookup"><span data-stu-id="0746f-137">Handling exceptions inside a workflow is performed with the <xref:System.Activities.Statements.TryCatch> activity.</span></span> <span data-ttu-id="0746f-138"><xref:System.Activities.Statements.TryCatch> Etkinliği olan bir <xref:System.Activities.Statements.TryCatch.Catches%2A> koleksiyonu <xref:System.Activities.Statements.Catch> her etkinlikleri ile belirli bir ilişkili <xref:System.Exception> türü.</span><span class="sxs-lookup"><span data-stu-id="0746f-138">The <xref:System.Activities.Statements.TryCatch> activity has a <xref:System.Activities.Statements.TryCatch.Catches%2A> collection of <xref:System.Activities.Statements.Catch> activities that are each associated with a specific <xref:System.Exception> type.</span></span> <span data-ttu-id="0746f-139">Varsa bulunan bir etkinlik tarafından oluşturulan özel durum <xref:System.Activities.Statements.TryCatch.Try%2A> bölümünü bir <xref:System.Activities.Statements.TryCatch> etkinlik özel durumu ile eşleşen bir <xref:System.Activities.Statements.Catch%601> etkinliğinde <xref:System.Activities.Statements.TryCatch.Catches%2A> koleksiyonu sonra özel durumu ele alınır.</span><span class="sxs-lookup"><span data-stu-id="0746f-139">If the exception thrown by an activity that is contained in the <xref:System.Activities.Statements.TryCatch.Try%2A> section of a <xref:System.Activities.Statements.TryCatch> activity matches the exception of a <xref:System.Activities.Statements.Catch%601> activity in the <xref:System.Activities.Statements.TryCatch.Catches%2A> collection, then the exception is handled.</span></span> <span data-ttu-id="0746f-140">Özel durum açık olarak yeniden oluşturulur veya yeni bir özel durum oluşturulduktan sonra bu özel durum üst etkinliğe geçirir.</span><span class="sxs-lookup"><span data-stu-id="0746f-140">If the exception is explicitly re-thrown or a new exception is thrown then this exception passes up to the parent activity.</span></span> <span data-ttu-id="0746f-141">Aşağıdaki örnekte gösterildiği kod bir <xref:System.Activities.Statements.TryCatch> işler etkinliği bir <xref:System.ApplicationException> oluşturulan <xref:System.Activities.Statements.TryCatch.Try%2A> tarafından bölümünde bir <xref:System.Activities.Statements.Throw> etkinlik.</span><span class="sxs-lookup"><span data-stu-id="0746f-141">The following code example shows a <xref:System.Activities.Statements.TryCatch> activity that handles an <xref:System.ApplicationException> that is thrown in the <xref:System.Activities.Statements.TryCatch.Try%2A> section by a <xref:System.Activities.Statements.Throw> activity.</span></span> <span data-ttu-id="0746f-142">Özel durum iletisi Konsolu tarafından yazılan <xref:System.Activities.Statements.Catch%601> etkinliği ve bir ileti yazılır konsolda <xref:System.Activities.Statements.TryCatch.Finally%2A> bölümü.</span><span class="sxs-lookup"><span data-stu-id="0746f-142">The exception's message is written to the console by the <xref:System.Activities.Statements.Catch%601> activity, and then a message is written to the console in the <xref:System.Activities.Statements.TryCatch.Finally%2A> section.</span></span>  
  
 [!code-csharp[CFX_WorkflowApplicationExample#33](../../../samples/snippets/csharp/VS_Snippets_CFX/cfx_workflowapplicationexample/cs/program.cs#33)]  
  
 <span data-ttu-id="0746f-143">Etkinlikler <xref:System.Activities.Statements.TryCatch.Finally%2A> bölümü olan yürütülmesi ya da <xref:System.Activities.Statements.TryCatch.Try%2A> bölüm veya <xref:System.Activities.Statements.TryCatch.Catches%2A> bölümü başarıyla tamamlanır.</span><span class="sxs-lookup"><span data-stu-id="0746f-143">The activities in the <xref:System.Activities.Statements.TryCatch.Finally%2A> section are executed when either the <xref:System.Activities.Statements.TryCatch.Try%2A> section or the <xref:System.Activities.Statements.TryCatch.Catches%2A> section successfully completes.</span></span> <span data-ttu-id="0746f-144"><xref:System.Activities.Statements.TryCatch.Try%2A> Bölümü başarıyla tamamlanırsa hiçbir ondan, özel durumlar varsa ve <xref:System.Activities.Statements.TryCatch.Catches%2A> bölümü başarıyla tamamlandığında durum ya da ondan işlenemezse hiçbir özel durum.</span><span class="sxs-lookup"><span data-stu-id="0746f-144">The <xref:System.Activities.Statements.TryCatch.Try%2A> section successfully completes if no exceptions are thrown from it, and the <xref:System.Activities.Statements.TryCatch.Catches%2A> section successfully completes if no exceptions are thrown or rethrown from it.</span></span> <span data-ttu-id="0746f-145">Bir özel durum, <xref:System.Activities.Statements.TryCatch.Try%2A> bölümünü bir <xref:System.Activities.Statements.TryCatch> ve ya da tarafından işlenmez bir <xref:System.Activities.Statements.Catch%601> içinde <xref:System.Activities.Statements.TryCatch.Catches%2A> bölümünde veya gelen işlenemezse <xref:System.Activities.Statements.TryCatch.Catches%2A>, etkinlikler <xref:System.Activities.Statements.TryCatch.Finally%2A> sürece çalıştırılmayacak aşağıdakilerden biri gerçekleşir.</span><span class="sxs-lookup"><span data-stu-id="0746f-145">If an exception is thrown in the <xref:System.Activities.Statements.TryCatch.Try%2A> section of a <xref:System.Activities.Statements.TryCatch> and is either not handled by a <xref:System.Activities.Statements.Catch%601> in the <xref:System.Activities.Statements.TryCatch.Catches%2A> section, or is rethrown from the <xref:System.Activities.Statements.TryCatch.Catches%2A>, the activities in the <xref:System.Activities.Statements.TryCatch.Finally%2A> will not be executed unless the one of the following occurs.</span></span>  
  
-   <span data-ttu-id="0746f-146">Daha yüksek bir düzeye göre özel durum yakalandı <xref:System.Activities.Statements.TryCatch> olup, daha yüksek bir düzeyinden işlenemezse bağımsız olarak iş akışında etkinlik <xref:System.Activities.Statements.TryCatch>.</span><span class="sxs-lookup"><span data-stu-id="0746f-146">The exception is caught by a higher level <xref:System.Activities.Statements.TryCatch> activity in the workflow, regardless of whether it is rethrown from that higher level <xref:System.Activities.Statements.TryCatch>.</span></span>  
  
-   <span data-ttu-id="0746f-147">Özel durum tarafından daha yüksek bir düzeye işlenmemiş <xref:System.Activities.Statements.TryCatch>, çıkışları iş akışı ve iş akışı kökündeki Sonlandır yerine iptal edin veya iptal etmek üzere yapılandırılmış.</span><span class="sxs-lookup"><span data-stu-id="0746f-147">The exception is not handled by a higher level <xref:System.Activities.Statements.TryCatch>, escapes the root of the workflow, and the workflow is configured to cancel instead of terminate or abort.</span></span> <span data-ttu-id="0746f-148">İş akışlarını kullanarak barındırılan <xref:System.Activities.WorkflowApplication> işleyerek yapılandırabilirsiniz <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> ve döndürme <xref:System.Activities.UnhandledExceptionAction.Cancel>.</span><span class="sxs-lookup"><span data-stu-id="0746f-148">Workflows hosted using <xref:System.Activities.WorkflowApplication> can configure this by handling <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> and returning <xref:System.Activities.UnhandledExceptionAction.Cancel>.</span></span> <span data-ttu-id="0746f-149">İşleme örneği <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> bu konuda daha önce sağlanan.</span><span class="sxs-lookup"><span data-stu-id="0746f-149">An example of handling <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> is provided previously in this topic.</span></span> <span data-ttu-id="0746f-150">İş akışı Hizmetleri bu kullanarak konusunda yapılandırabilir <xref:System.ServiceModel.Activities.Description.WorkflowUnhandledExceptionBehavior> ve belirterek <xref:System.ServiceModel.Activities.Description.WorkflowUnhandledExceptionAction.Cancel>.</span><span class="sxs-lookup"><span data-stu-id="0746f-150">Workflow services can configure this by using <xref:System.ServiceModel.Activities.Description.WorkflowUnhandledExceptionBehavior> and specifying <xref:System.ServiceModel.Activities.Description.WorkflowUnhandledExceptionAction.Cancel>.</span></span> <span data-ttu-id="0746f-151">Yapılandırma örneği için <xref:System.ServiceModel.Activities.Description.WorkflowUnhandledExceptionBehavior>, bkz: [iş akışı hizmeti konak genişletilebilirliği](../../../docs/framework/wcf/feature-details/workflow-service-host-extensibility.md).</span><span class="sxs-lookup"><span data-stu-id="0746f-151">For an example of configuring <xref:System.ServiceModel.Activities.Description.WorkflowUnhandledExceptionBehavior>, see [Workflow Service Host Extensibility](../../../docs/framework/wcf/feature-details/workflow-service-host-extensibility.md).</span></span>  
  
## <a name="exception-handling-versus-compensation"></a><span data-ttu-id="0746f-152">Özel durum işleme maaş</span><span class="sxs-lookup"><span data-stu-id="0746f-152">Exception Handling versus Compensation</span></span>  
 <span data-ttu-id="0746f-153">Özel durum işleme ve Dengeleme arasındaki farkı özel durum işleme sırasında bir etkinlik yürütülmesini gerçekleşir.</span><span class="sxs-lookup"><span data-stu-id="0746f-153">The difference between exception handling and compensation is that exception handling occurs during the execution of an activity.</span></span> <span data-ttu-id="0746f-154">Bir etkinliği başarıyla tamamlandıktan sonra maaş oluşur.</span><span class="sxs-lookup"><span data-stu-id="0746f-154">Compensation occurs after an activity has successfully completed.</span></span> <span data-ttu-id="0746f-155">Özel durum işleme etkinlik özel durumu tetikler sonra maaş tarafından önceden tamamlanmış bir etkinliğin başarıyla tamamlanan iş alınabilecek bir mekanizma sağlar ancak temizleme fırsatı sağlar.</span><span class="sxs-lookup"><span data-stu-id="0746f-155">Exception handling provides an opportunity to clean up after the activity raises the exception, whereas compensation provides a mechanism by which the successfully completed work of a previously completed activity can be undone.</span></span> <span data-ttu-id="0746f-156">Daha fazla bilgi için bkz: [maaş](../../../docs/framework/windows-workflow-foundation/compensation.md).</span><span class="sxs-lookup"><span data-stu-id="0746f-156">For more information, see [Compensation](../../../docs/framework/windows-workflow-foundation/compensation.md).</span></span>  
  
## <a name="see-also"></a><span data-ttu-id="0746f-157">Ayrıca Bkz.</span><span class="sxs-lookup"><span data-stu-id="0746f-157">See Also</span></span>  
 <xref:System.Activities.Statements.TryCatch>  
 <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A>  
 <xref:System.Activities.Statements.CompensableActivity>
